---
name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - '**/main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-24.04
    steps:
      # Checkout Repository (quickest possible mode)
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Blobless checkout to avoid downloading large files. This makes the
          # clone 2-4x faster. https://github.com/actions/checkout/pull/1396
          filter: blob:none

      # Setup requirements, i.e. python, pre-commit
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install pre-commit
        run: |
          python -m pip install pre-commit

      # Run pre-commit hooks
      - name: Run pre-commit
        run: |
          pre-commit run --all-files
          pre-commit run --config=.github/pre-commit-config.yaml --all-files --verbose
